# Water point-level headline results

## Number of people using DSW/ILC

### Prepare data

```{r}
hh_census_wp <-
  hh_census %>%
  left_join(wp_sample_sizes) 
```

#### Main treatment
 
```{r}
users_data_wp <-
  hh_census_wp %>%
  dplyr::filter(
    wp_intervention_type != "Non-program",
    !(sample_group != "ILC" & wp_intervention == "ILC"),
    # These are households using water points outside of the village
    # that were found to have DSW. Since we don't have a water point ID
    # for them, we cannot used them fow water point-level estimates
    !is.na(wp_id)
  ) %>%
  left_join(
    wp_census %>%
      dplyr::filter(dsw | ilc_wcp) %>%
      rename(wp_intervention = intervention) %>%
      group_by(country, sample_group, wp_intervention) %>%
      summarise(
        func_rate = mean(wp_func, na.rm = TRUE)
      )
  ) %>%
  group_by(country, sample_group, wp_intervention) %>%
  mutate(
    func_points = func_rate * pop_points,
    weight = n_distinct(wp_id)/func_points,
    weight_nofunc = n_distinct(wp_id)/pop_points
  ) %>% 
  ungroup
```

```{r}
users_data_wp <-
  users_data_wp %>%
  group_by(country, sample_group) %>%
  mutate(
    hh_members = if_else(
      !is.na(hh_members), 
      hh_members, 
      mean(hh_members, na.rm = TRUE)
    ),
    hh_members_increased = hh_members/response_rate
  ) 
```

### Sanity check

```{r}
group <-
  users_data_wp %>%
  group_by(
    wp_id, wp_intervention, sample_group, country, pop_points, func_points
  ) %>%
  summarise(
    users = sum(hh_members),
    users_increased = sum(hh_members_increased)
  ) %>%
  group_by(
    country, sample_group, wp_intervention, pop_points, func_points
  ) %>%
  summarise(
    across(
      c(users, users_increased),
      ~ mean(.)
    )
  ) %>%
  mutate(
    across(
      c(users, users_increased),
      ~ . * pop_points,
      .names = "{.col}_total"
    ),
    across(
      c(users, users_increased),
      ~ . * func_points,
      .names = "{.col}_func"
    )
  )

group
```

```{r}
group %>%
  group_by(wp_intervention, country) %>%
  summarise(
    across(
      c(contains("users_")),
      ~ sum(.)
    )
  ) %>%
  select(-users_increased)
```

### Final numbers

```{r}
users_wp <-
  users_data_wp %>%
  group_by(
    country, sample_group, wp_intervention
  ) %>%
  group_split %>%
  map(
    ~ total_cis(
      outcomes = c("hh_members_increased"),
      design = svydesign(
        id = ~ village_id + wp_id, # cluster IDs
        strata = ~ sample_group,
        prob = ~ weight,
        data = .x,
        nest = TRUE
      )
    ) %>%
      mutate(
        country = .x %>% pull(country) %>% unique,
        sample_group = .x %>% pull(sample_group) %>% unique,
        wp_intervention = .x %>% pull(wp_intervention) %>% unique,
        villages = .x %>% pull(village_id) %>% n_distinct,
        hhs = .x %>% pull(household_id) %>% n_distinct,
        wps = .x %>% pull(wp_id) %>% n_distinct,
      )
  ) %>% 
  bind_rows() %>%
  select(country, sample_group, wp_intervention, outcome, everything()) %>%
  arrange(outcome)
```

```{r}
users_wp_country <-
  users_data_wp %>%
  group_by(
    country, wp_intervention
  ) %>%
  group_split %>%
  map(
    ~ total_cis(
      outcomes = c("hh_members_increased"),
      design = svydesign(
        id = ~ village_id + wp_id, # cluster IDs
        strata = ~ sample_group,
        prob = ~ weight,
        data = .x,
        nest = TRUE
      )
    ) %>%
      mutate(
        country = .x %>% pull(country) %>% unique,
        wp_intervention = .x %>% pull(wp_intervention) %>% unique,
        villages = .x %>% pull(village_id) %>% n_distinct,
        hhs = .x %>% pull(household_id) %>% n_distinct,
        wps = .x %>% pull(wp_id) %>% n_distinct,
      )
  ) %>% 
  bind_rows() %>%
  select(country, wp_intervention, outcome, everything()) %>%
  arrange(outcome)
```

```{r}
users_wp %>%
  bind_rows(users_wp_country) %>%
  write_csv(
    here(
      "../output/tables/users-wp.csv"
    )
  )
```

## Chlorination rates

### Prepare data

```{r}
hh_survey_wp <-
  hh_survey %>%
  left_join(wp_sample_sizes)
```

```{r}
chlorination_data <-
  hh_survey_wp %>%
  dplyr::filter(
    wp_intervention_type != "Non-program",
    !(sample_group != "ILC" & wp_intervention == "ILC")
  )
```

```{r}
chlorination_data <-
  chlorination_data %>%
  # Sampling weights
  group_by(wp_id) %>%
  mutate(
    n_cl = n_distinct(household_id)
  ) %>%
  group_by(country, sample_group, wp_intervention) %>%
  mutate(
    n_cat = n_distinct(wp_id)
  ) %>%
  # Weight by number of users
  left_join(
    hh_census %>%
      group_by(wp_id) %>%
      summarise(
        n_users = n_distinct(household_id)
      )
  ) %>%
  ungroup %>%
  mutate(
    # Number of households using this water point represented by the observation
    weight_obs = n_users/n_cl,
    # Weighting all water points equally,
    weight_wp = 1/n_cl
  )
```
### Sanity check

```{r}
chlorination_data %>%
  group_by(wp_id, wp_intervention, sample_group, country) %>%
  summarise(
    across(
      c("disctcr_02", "discfcr_02"),
      ~ mean(., na.rm = TRUE)
    ),
    hhs = n_distinct(household_id)
  ) %>%
  group_by(country, sample_group, wp_intervention) %>%
  summarise(
    across(
      c("disctcr_02", "discfcr_02"),
      ~ mean(., na.rm = TRUE)
    ),
    hhs = sum(hhs),
    wp_id = n_distinct(wp_id)
  )
```

### Final numbers

#### By program and sample group

```{r}
cl_wp_sample <-
  chlorination_data %>%
  group_by(
    country, wp_intervention, sample_group
  ) %>%
  group_split %>%
  map(
    ~ mean_cis(
      outcomes = c("disctcr_02", "discfcr_02"),
      design = svydesign(
        id = ~ village_id + wp_id, # cluster IDs
        data = .x,
        nest = TRUE
      ) 
    ) %>%
      mutate(
        country = .x %>% pull(country) %>% unique,
        wp_intervention = .x %>% pull(wp_intervention) %>% unique,
        sample_group = .x %>% pull(sample_group) %>% unique,
        wps = .x %>% pull(wp_id) %>% n_distinct,
        households = .x %>% pull(household_id) %>% n_distinct,
      )
  ) %>% 
  bind_rows() %>%
  select(country, wp_intervention, sample_group, outcome, everything()) %>%
  arrange(desc(outcome))
``` 

#### Separate ILC

```{r}
cl_wp_ilc <-
  chlorination_data %>%
  dplyr::filter(sample_group == "ILC") %>%
  group_by(
    country, wp_intervention_type
  ) %>%
  group_split %>%
  map(
    ~ mean_cis(
      outcomes = c("disctcr_02", "discfcr_02"),
      design = svydesign(
        id = ~ village_id + wp_id, # cluster IDs
        data = .x,
        nest = TRUE
      ) 
    ) %>%
      mutate(
        country = .x %>% pull(country) %>% unique,
        wp_intervention = .x %>% pull(wp_intervention_type) %>% unique,
        sample_group = .x %>% pull(sample_group) %>% unique,
        wps = .x %>% pull(wp_id) %>% n_distinct,
        households = .x %>% pull(household_id) %>% n_distinct,
      )
  ) %>% 
  bind_rows() %>%
  select(country, wp_intervention, sample_group, outcome, everything()) %>%
  arrange(desc(outcome))
``` 

#### By program

```{r}
cl_wp_noweights <-
  chlorination_data %>%
  group_by(
    country, wp_intervention
  ) %>%
  group_split %>%
  map(
    ~ mean_cis(
      outcomes = c("disctcr_02", "discfcr_02"),
      design = svydesign(
        id = ~ village_id + wp_id, # cluster IDs
        data = .x,
        nest = TRUE
      ) 
    ) %>%
      mutate(
        country = .x %>% pull(country) %>% unique,
        wp_intervention = .x %>% pull(wp_intervention) %>% unique,
        wps = .x %>% pull(wp_id) %>% n_distinct,
        households = .x %>% 
          dplyr::filter(!is.na(disctcr_02) | !is.na(discfcr_02)) %>%
          pull(household_id) %>% 
          n_distinct
      )
  ) %>% 
  bind_rows() %>%
  select(country, wp_intervention, outcome, everything()) %>%
  arrange(desc(outcome))
``` 

```{r}
cl_wp_noweights %>%
  bind_rows(cl_wp_ilc) %>%
  bind_rows(cl_wp_sample) %>%
  write_csv(
    here("../output/tables/chlorine-wp.csv")
  )
```

## Table

### By program

```{r, message = FALSE, warning = FALSE}
obs <-
  users_data_wp %>%
  dplyr::filter(!is.na(wp_id)) %>%
    group_by(
      country, wp_intervention
    ) %>%
    summarise(
      n_wps = n_distinct(wp_id),
      census = n_distinct(household_id) %>% format(big.mark = ",")
    ) %>%
    mutate(
      name = "est"
    )

people <-
  users_wp_country %>%
  left_join(
    wp_sample_sizes %>%
      group_by(country, wp_intervention) %>%
      summarise(pop = sum(pop_points))
  ) %>%
  mutate(
    across(
      c(total, lb, ub, pop),
      ~ . %>% 
        round %>% 
        format(big.mark = ",") %>%
        str_remove_all(" ")
    ),
    ci = paste0("(", lb, ", ", ub, ")") 
  ) %>%
  select(
    country, wp_intervention, pop, est = total, ci
  ) %>%
  pivot_longer(
    cols = c(est, ci),
    values_to = "people"
  ) 

cl <-
  cl_wp_noweights %>%
  mutate(
    across(
      c(mean, lb, ub),
      ~ (. * 100) %>% 
        round(1) %>% 
        str_remove_all(" ")
    ),
    ci = paste0("(", lb, ", ", ub, ")") ,
    hhs = households %>% format(big.mark = ",")
  ) %>%
  select(country, wp_intervention, outcome, wps, hhs, est = mean, ci) %>%
  pivot_wider(
    values_from = c(est, ci),
    names_from = outcome
  ) %>%
  pivot_longer(
    cols = ends_with("02"),
    names_pattern = "(.*)_disc(.*)_02",
    names_to = c("name", ".value")
  )

tab <- 
  obs %>%
  full_join(people) %>%
  left_join(cl) %>%
  arrange(country, wp_intervention, desc(name)) %>%
  mutate(
    across(
      everything(),
      ~ as.character(.)
    ),
    across(
      -c(people, tcr, fcr),
      ~ case_when(
        name == "est" ~ .,
        TRUE ~ ""
      )
    )
  ) %>%
  ungroup %>%
  select(-c(name, country))

table <-
  kable(
    tab, 
    format = "latex",
    escape = F,
    align = "c", 
    booktabs = T,
    col.names = linebreak(
      c("Intervention", "\\#WPs", "\\#HHs", "\\#WPs", "People using\nDSW/ILC\n(95\\% CI)", "\\#WPs", "\\#HHs", "TCR\n(95\\% CI)", "FCR\n(95\\% CI)"),
      align = "c"
    ),
    caption = "Primary outcomes estimated using the water point as the unit of reference",
    label = "headlines-wp"
  ) %>%
  kable_styling(latex_options = c("scale_down")) %>%
  pack_rows("Malawi", 1, 4) %>%
  pack_rows("Uganda", 5, 6) %>%
  add_header_above(
    c(
      " ", 
      "Household census" = 2, 
      "Country-level estimates" = 2, 
      "Percent of color wheel readings ≥ 0.2 ppm" = 4
    )
  ) %>%
  add_header_above(c(" ", paste0("(", 1:8,")")), line = FALSE)

writeLines(
  table, 
  "output/tables/headlines-wp.tex"
)
```

### By program and sample group

```{r, message = FALSE, warning = FALSE}
obs <-
  users_data_wp %>%
  dplyr::filter(!is.na(wp_id)) %>%
    group_by(
      country, wp_intervention, sample_group
    ) %>%
    summarise(
      n_wps = n_distinct(wp_id),
      census = n_distinct(household_id) %>% format(big.mark = ",")
    ) %>%
    mutate(
      name = "est"
    )

people <-
  users_wp %>%
  left_join(
    wp_sample_sizes %>%
      group_by(country, wp_intervention, sample_group) %>%
      summarise(pop = sum(pop_points))
  ) %>%
  mutate(
    across(
      c(total, lb, ub, pop),
      ~ . %>% 
        round %>% 
        format(big.mark = ",") %>%
        str_remove_all(" ")
    ),
    ci = paste0("(", lb, ", ", ub, ")") 
  ) %>%
  select(
    country, wp_intervention, sample_group, pop, est = total, ci
  ) %>%
  pivot_longer(
    cols = c(est, ci),
    values_to = "people"
  ) 

cl <-
  cl_wp_sample %>%
  mutate(
    across(
      c(mean, lb, ub),
      ~ (. * 100) %>% 
        round(1) %>% 
        str_remove_all(" ")
    ),
    ci = paste0("(", lb, ", ", ub, ")") ,
    hhs = households %>% format(big.mark = ",")
  ) %>%
  select(country, wp_intervention, sample_group, outcome, wps, hhs, est = mean, ci) %>%
  pivot_wider(
    values_from = c(est, ci),
    names_from = outcome
  ) %>%
  pivot_longer(
    cols = ends_with("02"),
    names_pattern = "(.*)_disc(.*)_02",
    names_to = c("name", ".value")
  )

tab <- 
  obs %>%
  full_join(people) %>%
  left_join(cl) %>%
  arrange(country, wp_intervention, sample_group, desc(name)) %>%
  ungroup %>%
  mutate(
    across(
      everything(),
      ~ as.character(.)
    ),
    across(
      -c(people, tcr, fcr),
      ~ case_when(
        name == "est" ~ .,
        TRUE ~ ""
      )
    )
  ) %>%
  select(-c(name, country)) 

table <-
  kable(
    tab, 
    format = "latex",
    escape = F,
    align = "c", 
    booktabs = T,
    col.names = linebreak(
      c(" ", "Sample group", "\\#WP", "\\#HH", "\\#WP", "People using\nDSW/ILC\n(95\\% CI)", "\\#WP", "\\#HH", "TCR\n(95\\% CI)", "FCR\n(95\\% CI)"),
      align = "c"
    ),
    caption = "Primary outcomes estimated using the water point as the unit of reference",
    label = "headlines-wp-by-group"
  ) %>%
  kable_styling(latex_options = c("scale_down")) %>%
  pack_rows("Malawi", 1, 8) %>%
  pack_rows("Uganda", 9, 12) %>%
  add_header_above(
    c(
      " " = 2, 
      "Household census" = 2, 
      "Country-level estimates" = 2, 
      "Percent of color wheel readings ≥ 0.2 ppm" = 4
    )
  ) %>%
  add_header_above(c(" ", " ", paste0("(", 1:8,")")), line = FALSE)

writeLines(
  table, 
  "output/tables/headlines-wp-by-group.tex"
)
```

