# DSW water points

```{r}
dsw <-
  wp_census %>%
  dplyr::filter(intervention_type == "DSW")
```

## Functionality 

### By sample group

```{r}
evac <-
  villages %>%
  select(country, sample_group, village_id, dsw_wpt) %>%
  dplyr::filter(village_id %in% dsw$village_id) %>%
  group_by(country, sample_group) %>%
  summarise(
    dsw_wpt = sum(dsw_wpt)
  )

headers <- c(
  " " = 2,
  "Number of WPs" = 2,
  "Percent of water points in the census" = 6
)
columns_9 <- c(" ", paste0("(", 1:9,")"))
caption <- "DSW functionality indicators"
footnote_text <-
  "The sample includes all water points in the water point census, some of which are located outside of village boundaries. The denominator for columns (4) to (8) is the number of water points with DSW in the census, shown in column (3). A dispenser is considered to be filled if chlorine was released after turning the valve. This is different from the definition used by Evidence Action in their Adoption Monitoring, when surveyors open the dispenser casing to check if there is chlorine in the tank. Therefore, the numbers in column (9) correspond to functional and filled dispensers in Evidence Action's data."

dsw_func <-
  dsw %>%
  group_by(country, sample_group) %>%
  summarise(
    Villages = n_distinct(village_id),
    `WP census` = n_distinct(wp_id),
    `Matched to EvAc data` = sum(!is.na(ea_id)),
    `WP functional` = sum(wp_func, na.rm = TRUE),
    `Casing present` = sum(disp_casing_present, na.rm = TRUE),
    `Tank present` = sum(disp_tank_present, na.rm = TRUE),
    `Dispenser functional` = sum(disp_func, na.rm = TRUE),
    `Dispenser filled` = sum(disp_filled, na.rm = TRUE)
  ) %>%
  mutate(
    across(
      `Matched to EvAc data`:`Dispenser filled`,
      ~ round(. * 100/`WP census`, 1)
    )
  ) %>%
  ungroup %>%
  left_join(evac) %>%
  select(-country) %>%
  select(Sample = sample_group, Villages, `EvAc data` = dsw_wpt, everything())



dsw_func %>%
  html_table(
    single_footnote = footnote_text,
    caption = caption
  ) %>%
  pack_sample %>%
  add_header_above(headers, line = TRUE) %>%
  add_header_above(columns_9, line = FALSE)
```

```{r}
latex_table(
  dsw_func,
  align = "lccccccccc", 
  caption = caption,
  label = "dsw-func-group",
  single_footnote = footnote_text
) %>%
  pack_sample %>%
  add_header_above(headers, line = TRUE) %>%
  add_header_above(columns_9, line = FALSE) %>%
  column_spec(c(2, 4, 7, 8, 10), width = "1.5cm") %>%
  column_spec(3, width = "1cm") %>%
  column_spec(c(5, 6, 9), width = "2cm") %>%
  writeLines(
    "output/appendix-tables/dsw-func-group.tex"
  )
```

### By country

```{r}
evac <-
  villages %>%
  select(country, village_id, dsw_wpt) %>%
  dplyr::filter(village_id %in% dsw$village_id) %>%
  group_by(country) %>%
  summarise(
    dsw_wpt = sum(dsw_wpt)
  )

dsw_func <-
  dsw %>%
  group_by(country) %>%
  summarise(
    Villages = n_distinct(village_id),
    `WP census` = n_distinct(wp_id),
    `Matched to EvAc data` = sum(!is.na(ea_id)),
    `WP functional` = sum(wp_func, na.rm = TRUE),
    `Casing present` = sum(disp_casing_present, na.rm = TRUE),
    `Tank present` = sum(disp_tank_present, na.rm = TRUE),
    `Dispenser functional` = sum(disp_func, na.rm = TRUE),
    `Dispenser filled` = sum(disp_filled, na.rm = TRUE)
  ) %>%
  mutate(
    across(
      `Matched to EvAc data`:`Dispenser filled`,
      ~ round(. * 100/`WP census`, 1)
    )
  ) %>%
  left_join(evac) %>%
  select(Country = country, Villages, `EvAc data` = dsw_wpt, everything())

headers <- c(
  " " = 2,
  "Number of WPs" = 2,
  "Percent of water points in the census" = 6
)
caption <- "DSW functionality indicators"

dsw_func %>%
  html_table(
    single_footnote = footnote_text,
    caption = caption
  ) %>%
  add_header_above(headers, line = TRUE) %>%
  add_header_above(columns_9, line = FALSE)
```

```{r}
dsw_func %>% 
  select(-`Casing present`) %>%
  latex_table(
    align = "lccccccccc",
    caption = caption,
    label = "dsw-func",
    single_footnote = footnote_text
  ) %>%
  add_header_above(
    c(
      " " = 2,
      "Number of WPs" = 2,
      "Percent of water points in the census" = 5
    ),
    line = TRUE
  ) %>%
  add_header_above(columns_8, line = FALSE) %>%
  column_spec(c(1:4), width = "1.5cm") %>%
  column_spec(c(5:9), width = "2cm") %>%
  writeLines(
    "output/tables/dsw-func.tex"
  )
```


```{r}
dsw %>%
  mutate(
    sample_group = factor(sample_group, ordered = FALSE)
  ) %>%
  group_by(country) %>%
  group_split %>%
  map(
    ~ feols(
      disp_filled ~ sample_group,
      cluster = ~ village_id,
      data = .
    ) 
  ) %>%
  set_names(
    c("Malawi", "Uganda")
  ) %>%
  modelsummary(
    stars = TRUE,
    coef_map = 
      c(
        "(Intercept)" = "(Intercept)",
        "sample_groupExpansion" = "Expansion",
        "sample_groupILC" = "ILC"
      ),
    title = "Regression of indicator for filled dispenser on sample group",
    gof_omit = "BIC|AIC|RMSE"
  ) %>%
  style_tt(bootstrap_class = "table caption-top")
```

## Dosing

### By sample group

```{r}
dosing <-
 dsw %>%
  group_by(country, sample_group) %>%
  summarise(
    disp_filled = sum(disp_filled, na.rm = TRUE),
    across(
      c(disctcr_02, discfcr_02, metertcr_02, meterfcr_02, metertcr_01, meterfcr_01),
      list(
        n = ~ sum(!is.na(.)),
        pct = ~ paste0(round((mean(., na.rm = TRUE) * 100), 1), "%")
      )
    )
  ) %>%
  ungroup %>%
  select(
    sample_group, disp_filled, 
    contains("disctcr"), contains("discfcr"), 
    contains("metertcr"), contains("meterfcr"),
    -matches("meter()(.*)_01_n"),
    -discfcr_02_n, -meterfcr_02_n
  ) %>%
  set_names(c("Sample group", "Filled dispenser", "N", "TCR ≥ 0.2 mg/L", "FCR ≥ 0.2 mg/L", "N", "TCR ≥ 0.2 mg/L", "TCR ≥ 0.1 mg/L", "FCR ≥ 0.2 mg/L", "FCR ≥ 0.1 mg/L"))

footnote_text <-
  "At each water point with a filled dispenser, water was collected using a 20 liter jerrycan, dilute chlorine solution from the dispenser was added to the water, and the chlorine residual was measured using a color wheel 30 minutes after the water water treated."
caption <- "Chlorine detection rates at water points with DSW"
headers <- 
  c(
    " " = 2,
    "Color wheel" = 3,
    "Colorimeter" = 5
  )
```

```{r}
dosing %>%
  html_table(
    single_footnote = footnote_text
  ) %>%
  pack_sample %>%
  add_header_above(headers, line = TRUE) %>%
  add_header_above(columns_9, line = FALSE) 
```

```{r}
columns_4 <- c(" ", paste0("(", 1:4,")"))

dosing %>%
  select(1:5) %>%
  latex_table(
    numbered_footnote = c("All TCR readings were taken with a color wheel.", footnote_text),
    label = "dsw-cl-group",
    align = "lcccc",
    caption = caption
  ) %>%
  pack_sample %>%
  add_header_above(columns_4, line = FALSE) %>%
  writeLines(
    "output/appendix-tables/dsw-cl-group.tex"
  )
```

### By country

```{r}
dosing <-
 dsw %>%
  group_by(country) %>%
  summarise(
    disp_filled = sum(disp_filled, na.rm = TRUE),
    across(
      c(disctcr_02, discfcr_02, metertcr_02, meterfcr_02, metertcr_01, meterfcr_01),
      list(
        n = ~ sum(!is.na(.)),
        pct = ~ paste0(round((mean(., na.rm = TRUE) * 100), 1), "%")
      )
    )
  ) %>%
  select(
    disp_filled, 
    contains("disctcr"), contains("discfcr"), 
    contains("metertcr"), contains("meterfcr"),
    -matches("meter()(.*)_01_n"),
    -discfcr_02_n, -meterfcr_02_n
  ) %>%
  set_names(c("Filled dispenser", "N", "TCR ≥ 0.2 mg/L", "FCR ≥ 0.2 mg/L", "N", "TCR ≥ 0.2 mg/L", "TCR ≥ 0.1 mg/L", "FCR ≥ 0.2 mg/L", "FCR ≥ 0.1 mg/L"))
```

```{r}
caption <- "Chlorine detection rates at water points with DSW"
header <- 
  c(
    " ",
    "Color wheel" = 3,
    "Colorimeter" = 5
  )

dosing %>%
  html_table(
    caption = caption,
    single_footnote = footnote_text
  ) %>%
  add_header_above(header, line = TRUE) %>%
  add_header_above(columns_8, line = FALSE)
```

```{r}
dosing %>%
  select(1:4) %>%
  mutate(Country = c("Malawi", "Uganda")) %>%
  select(Country, everything()) %>%
  latex_table(
    align = "lcccc",
    label = "dsw-cl",
    caption = caption,
    numbered_footnote = c("All TCR readings were taken with a color wheel.", footnote_text)
  ) %>%
  add_header_above(columns_4, line = FALSE) %>%
  writeLines(
    "output/tables/dsw-cl.tex"
  )
```


## Constraints to adoption

```{r}
hh_survey %>%
  dplyr::filter(
    wp_intervention == "DSW",
    wp_func
  ) %>%
  inner_join(
    wp_census %>%
      dplyr::filter(!disp_filled) %>%
      select(wp_id)
  ) %>%
  group_by(country, sample_group) %>%
  group_split %>%
  map_dfr(
    ~ map_dfr(
      c("discfcr_02", "disctcr_02"),
      \(outcome) mean_ci(
        .x, 
        var = outcome
      ) %>%
      mutate(
        country = .x %>% pull(country) %>% unique,
        hhs = .x %>% pull(household_id) %>% n_distinct,
        villages = .x %>% pull(village_id) %>% n_distinct,
        sample_group = .x %>% pull(sample_group) %>% unique,
      )
    )
  ) %>%
  mutate(
    across(
      c(mean, lb, ub),
      ~ round(. * 100, 1) %>% as.character
    ),
    ci = paste0("(", lb, ", ", ub, ")")
  ) %>%
  select(country, sample_group, hhs, mean, ci, outcome) %>%
  pivot_longer(
    cols = c(mean, ci),
    names_to = "est"
  ) %>%
  pivot_wider(
    values_from = value,
    names_from = outcome
  ) %>%
  mutate(
    across(
      c(sample_group, hhs),
      ~ if_else(est == "mean", as.character(.), "")
    )
  ) %>%
  select(sample_group, hhs, disctcr_02, discfcr_02) %>%
  latex_table(
    caption = "Percent of color wheel readings ≥ 0.2 mg/L among households using water points with empty dispensers",
    label = "dsw-empty",
    escape = FALSE,
    col.names = linebreak(c("Sample group", "N", "TCR\n(95\\% CI)", "FCR\n(95\\% CI)")),
    single_footnote = "Sample includes all households in the Census Sample that were matched to a water points with DSW that was found to be functional (the valve could be turned), but empty (no chlorine was dispensed when turning the valve) during the Water Point Census."
  ) %>%
  pack_rows("Malawi", 1, 6) %>%
  pack_rows("Uganda", 7, 10) %>%
  add_header_above(c(" ", paste0("(", 1:3, ")")), line = FALSE) %>%
  writeLines(
    "output/appendix-tables/dsw-empty.tex"
  )
```


## Text


### Functionality rates among non-program WPs

```{r}
wp_census %>%
  dplyr::filter(intervention == "DSW") %>%
  summarise(
    (mean(disp_filled, na.rm = TRUE) * 100) %>% 
      round(1)
  ) 
```

```{r}
wp_census %>%
  dplyr::filter(intervention == "Non-program", sample_group == "ILC") %>%
  group_by(country) %>%
  summarise(
    (mean(wp_func, na.rm = TRUE) * 100) %>% 
      round(1)
  ) %>%
  kable(
    format = "html",
    col.names = c(" ", "Functional water points (%)")
  )
```

```{r}
wp_census %>%
  dplyr::filter(intervention == "Non-program", sample_group != "ILC") %>%
  group_by(country) %>%
  summarise(
    (mean(wp_func, na.rm = TRUE) * 100) %>% 
      round(1)
  ) %>%
  kable(
    format = "html",
    col.names = c(" ", "Functional water points (%)")
  )
```


```{r}
wp_census %>%
  dplyr::filter(
    intervention == "DSW"
  ) %>%
  group_by(country, sample_group) %>%
  summarise(
    (mean(disp_func, na.rm = TRUE) * 100) %>% 
      round(1)
  ) %>%
  kable(
    format = "html",
    col.names = c("Country", "Sample group", "Functional water points (%)")
  )
```

```{r}
wp_census %>%
  dplyr::filter(
    intervention == "DSW",
    disp_func
  ) %>%
  group_by(country, sample_group) %>%
  summarise(
    (mean(disp_filled, na.rm = TRUE) * 100) %>% 
      round(1)
  ) %>%
  kable(
    format = "html",
    col.names = c("Country", "Sample group", "Functional water points (%)")
  )
```

```{r}
wp_census %>%
  dplyr::filter(
    intervention == "DSW",
    disp_func
  ) %>%
  group_by(country) %>%
  summarise(
    (mean(disp_filled, na.rm = TRUE) * 100) %>% 
      round(1)
  ) %>%
  kable(
    format = "html",
    col.names = c("Country", "Functional water points (%)")
  )
```


```{r}
wp_census %>%
  dplyr::filter(
    intervention == "DSW"
  ) %>%
  mutate(discfcr_02 = replace_na(discfcr_02, FALSE)) %>%
  group_by(country, sample_group) %>%
  summarise(
    (mean(discfcr_02, na.rm = TRUE) * 100) %>% 
      round(1)
  ) %>%
  kable(
    format = "html",
    col.names = c("Country", "Sample group", "Functional water points (%)")
  )
```

```{r}
wp_census %>%
  dplyr::filter(
    intervention == "DSW"
  ) %>%
  mutate(discfcr_02 = replace_na(discfcr_02, FALSE)) %>%
  summarise(
    (mean(discfcr_02, na.rm = TRUE) * 100) %>% 
      round(1)
  )
```