# Chlorination rates under different criteria

```{r}
criteria <-
  c(
    "disctcr_02", "discfcr_02",
    "metertcr_02", "meterfcr_02",
    "metertcr_01", "meterfcr_01"
  )
```

## Number of observations

```{r}
obs <-
  chlorination_data %>%
  group_by(country, sample_group, wp_intervention) %>%
  summarise(
    across(
      all_of(criteria),
      ~ sum(!is.na(.))
    )
  )

obs_long <-
  obs %>%
  pivot_longer(
    cols = all_of(criteria),
    values_to = "N",
    names_to = "outcome"
  ) %>%
  mutate(
    N = format(N, big.mark = ",")
  )
```


## By sample group and program

```{r}
cl_criteria_group <-
  chlorination_data %>%
  group_by(country, sample_group, wp_intervention) %>%
  group_split %>%
  map(
    ~ mean_cis(
        outcomes = criteria,
        design = svydesign(
          id = ~ village_id + wp_id,      # PSU (here: villages)
          data = .,
          nest = TRUE
        )
    ) %>%
      mutate(
        country = .x %>% pull(country) %>% unique,
        sample_group = .x %>% pull(sample_group) %>% unique,
        wp_intervention = .x %>% pull(wp_intervention) %>% unique
      )
  ) %>%
  bind_rows %>%
  mutate(
    across(
      c(mean, lb, ub),
      ~ (. * 100) %>% round(1) %>% as.character
    ),
    ci = paste0("(", lb, ", ", ub, ")")
  ) %>%
  select(country, sample_group, wp_intervention, outcome, mean, ci) %>%
  pivot_longer(
    cols = c(mean, ci)
  ) %>%
  left_join(obs_long) %>%
  select(country, sample_group, wp_intervention, outcome, name, N, value) %>%
  pivot_wider(
    names_from = outcome,
    values_from = c(N, value)
  ) %>%
  mutate(
    across(
      c(wp_intervention, sample_group, starts_with("N")),
      ~ if_else(name == "ci", "", .)
    )
  ) %>%
  ungroup %>%
  select(
    sample_group,
    wp_intervention,
    matches(criteria)
  )

table <-
  kable(
    cl_criteria_group, 
    format = "latex",
    escape = F,
    align = "c", 
    booktabs = T,
    col.names = linebreak(
      c("Sample group", "Intervention", 
        "N", "\\%\n(95\\% CI)",
        "N", "\\%\n(95\\% CI)",
        "N", "\\%\n(95\\% CI)",
        "N", "\\%\n(95\\% CI)",
        "N", "\\%\n(95\\% CI)",
        "N", "\\%\n(95\\% CI)"
      ),
      align = "c"
    ),
    caption = "Percent of households where chlorine residual was detected under different thresholds, by sample group and intervention",
    label = "cl-criteria-sample"
  ) %>%
  kable_styling(latex_options = c("scale_down")) %>%
  pack_rows("Malawi", 1, 8) %>%
  pack_rows("Uganda", 9, 12) %>%
  add_header_above(
    c(
      " " = 2, 
      "TCR > 0.2 ppm" = 2,
      "FCR > 0.2 ppm" = 2,
      "TCR > 0.2 ppm" = 2,
      "FCR > 0.2 ppm" = 2,
      "TCR > 0.1 ppm" = 2,
      "FCR > 0.1 ppm" = 2
    )
  )

writeLines(
  table, 
  "output/appendix-tables/cl-criteria-sample.tex"
)
```

## By country and program

```{r}
obs <-
  obs %>%
  group_by(country, wp_intervention) %>%
  summarise(
    across(
      -sample_group,
      ~ sum(.)
    )
  ) %>%
  pivot_longer(
    cols = -c(country, wp_intervention),
    values_to = "N",
    names_to = "outcome"
  )
  
est <-
  chlorination_data %>%
  group_by(country, wp_intervention) %>%
  group_split %>%
  map(
    ~ mean_cis(
        outcomes = criteria,
        design = svydesign(
          id = ~ village_id + wp_id,      # PSU (here: villages)
          data = .,
          nest = TRUE
        )
    ) %>%
      mutate(
        country = .x %>% pull(country) %>% unique,
        wp_intervention = .x %>% pull(wp_intervention) %>% unique
      )
  ) %>%
  bind_rows %>%
  mutate(
    across(
      c(mean, lb, ub),
      ~ (. * 100) %>% round(1) %>% as.character
    ),
    ci = paste0("(", lb, ", ", ub, ")")
  ) %>%
  select(country, wp_intervention, outcome, mean, ci) %>%
  pivot_longer(
    cols = c(mean, ci)
  ) %>%
  left_join(obs) %>%
  select(country, wp_intervention, outcome, name, N, value) %>%
  pivot_wider(
    names_from = outcome,
    values_from = c(N, value)
  ) %>%
  mutate(
    across(
      c(wp_intervention, starts_with("N")),
      ~ if_else(name == "ci", "", format(., big.mark = ","))
    )
  ) %>%
  ungroup %>%
  select(
    wp_intervention,
    matches(criteria)
  )
  
table <-
  kable(
    est, 
    format = "latex",
    escape = F,
    align = "c", 
    booktabs = T,
    col.names = linebreak(
      c("Intervention", 
        "N", "\\%\n(95\\% CI)",
        "N", "\\%\n(95\\% CI)",
        "N", "\\%\n(95\\% CI)",
        "N", "\\%\n(95\\% CI)",
        "N", "\\%\n(95\\% CI)",
        "N", "\\%\n(95\\% CI)"
      ),
      align = "c"
    ),
    caption = "Percent of households where chlorine residual was detected under different thresholds, by intervention",
    label = "cl-criteria-country"
  ) %>%
  kable_styling(latex_options = c("scale_up")) %>%
  pack_rows("Malawi", 1, 4) %>%
  pack_rows("Uganda", 5, 6) %>%
  add_header_above(
    c(
      " ", 
      "TCR > 0.2 ppm" = 2,
      "FCR > 0.2 ppm" = 2,
      "TCR > 0.2 ppm" = 2,
      "FCR > 0.2 ppm" = 2,
      "TCR > 0.1 ppm" = 2,
      "FCR > 0.1 ppm" = 2
    )
  )

writeLines(
  table, 
  "output/appendix-tables/cl-criteria-country.tex"
)
```

