---
output:
pdf_document: default
html_document: default
---

# Sample sizes
  
```{r}
packages <-
  c(
    "stringr",
    "sf",
    "tidyverse",
    "viridis",
    "janitor"
  )

pacman::p_load(
  packages,
  character.only = TRUE
)
```


## Water points 

```{r}
wp <-
  read_rds(
    file.path(
      path_box,
      "Data",
      "WaterPointCensus",
      "DataSets",
      "Final",
      "wp-census.rds"
    )
  )

wp %>%
  group_by(country) %>%
  summarise(
    Villages = n_distinct(village_id),
    `Water points` = n_distinct(wp_id),
    ILC = sum(str_detect(intervention_type, "ILC"), na.rm = TRUE),
    DSW = sum(intervention_type == "DSW", na.rm = TRUE),
    `Color wheel FCR test` = sum(!is.na(discfcr)),
    `Color wheel TCR test` = sum(!is.na(disctcr)),
    `Colorimeter FCR test` = sum(!is.na(meterfcr)),
    `Colorimeter TCR test` = sum(!is.na(metertcr)),
  ) %>%
  pivot_longer(cols = -country) %>%
  pivot_wider(
    names_from = country,
    values_from = value
  ) %>%
  kable(
    caption = "Average share of households that has at least 0.2 ppm of TCR on color wheel",
      col.names = c("Sample", "Malawi", "Uganda"),
      align = c("l", "c", "c")
  ) %>%
  kable_styling(
    full_width = FALSE, 
    bootstrap_options = c("striped", "hover")
  )
```

## Household survey

```{r}
hh_survey <-
  read_rds(
    file.path(
      path_box,
      "Data",
      "HouseholdSurvey",
      "DataSets",
      "Final",
      "hh-survey.rds"
    )
  ) %>%
  dplyr::filter(survey == "Household Survey")

hh_survey %>%
  group_by(country) %>%
  summarise(
    Villages = n_distinct(village_id),
    Household = n_distinct(household_id),
    ILC = sum(str_detect(wp_intervention_type, "ILC"), na.rm = TRUE),
    DSW = sum(wp_intervention_type == "DSW", na.rm = TRUE),
    `Color wheel FCR test` = sum(!is.na(discfcr)),
    `Color wheel TCR test` = sum(!is.na(disctcr)),
    `Colorimeter FCR test` = sum(!is.na(meterfcr)),
    `Colorimeter TCR test` = sum(!is.na(metertcr)),
  ) %>%
  pivot_longer(cols = -country) %>%
  pivot_wider(
    names_from = country,
    values_from = value
  )  %>%
  kable(
    caption = "Number of observations in household survey",
      col.names = c("", "Malawi", "Uganda"),
      align = c("l", "c", "c")
  ) %>%
  kable_styling(
    full_width = FALSE, 
    bootstrap_options = c("striped", "hover")
  )
```

## Monitoring survey

```{r}
mon_survey <-
  read_rds(
    file.path(
      path_box,
      "Data",
      "HouseholdSurvey",
      "DataSets",
      "Final",
      "hh-survey.rds"
    )
  ) %>%
  dplyr::filter(survey == "Monitoring Survey")

mon_survey %>%
  group_by(country) %>%
  summarise(
    Villages = n_distinct(village_id),
    Household = n_distinct(household_id),
    ILC = sum(str_detect(wp_intervention_type, "ILC"), na.rm = TRUE),
    DSW = sum(wp_intervention_type == "DSW", na.rm = TRUE),
    `Color wheel FCR test` = sum(!is.na(discfcr)),
    `Color wheel TCR test` = sum(!is.na(disctcr)),
    `Colorimeter FCR test` = sum(!is.na(meterfcr)),
    `Colorimeter TCR test` = sum(!is.na(metertcr)),
  ) %>%
  pivot_longer(cols = -country) %>%
  pivot_wider(
    names_from = country,
    values_from = value
  )
```
## Chlorine tests

```{r}
wp %>%
  group_by(country, intervention_type) %>%
  summarise(
    `Color wheel FCR test` = sum(!is.na(discfcr)),
    `Color wheel TCR test` = sum(!is.na(disctcr)),
    `Colorimeter FCR test` = sum(!is.na(meterfcr)),
    `Colorimeter TCR test` = sum(!is.na(metertcr)),
  )
```

```{r}
read_rds(
    file.path(
      path_box,
      "Data",
      "HouseholdSurvey",
      "DataSets",
      "Final",
      "hh-survey.rds"
    )
  ) %>%
  group_by(country, wp_intervention_type) %>%
  summarise(
    `Color wheel FCR test` = sum(!is.na(discfcr)),
    `Color wheel TCR test` = sum(!is.na(disctcr)),
    `Colorimeter FCR test` = sum(!is.na(meterfcr)),
    `Colorimeter TCR test` = sum(!is.na(metertcr)),
  )
```

```{r}
read_rds(
    file.path(
      path_box,
      "Data",
      "HouseholdSurvey",
      "DataSets",
      "Final",
      "hh-survey.rds"
    )
  ) %>%
  group_by(country) %>%
  summarise(
    `Color wheel FCR test` = sum(!is.na(discfcr)),
    `Color wheel TCR test` = sum(!is.na(disctcr)),
    `Colorimeter FCR test` = sum(!is.na(meterfcr)),
    `Colorimeter TCR test` = sum(!is.na(metertcr)),
  )
```

## Potential contamination

```{r}
hh_survey %>%
  dplyr::filter(!is.na(int_warned)) %>%
  tabyl(int_warned, country) %>%
  adorn_percentages(denominator = "col") %>%
  adorn_pct_formatting()
```

```{r}
hh_survey %>%
  dplyr::filter(int_warned == "Yes") %>%
  tabyl(int_warned_who, country)
```

```{r}
hh_survey %>%
  dplyr::filter(int_warned_who == "Other") %>%
  tabyl(int_warned_who_o, country)
```

```{r}
hh_survey %>%
  dplyr::filter(!is.na(int_warned_what)) %>%
  mutate(int_warner = if_else(int_warned_who != "Other", as.character(int_warned_who), int_warned_who_o)) %>%
  select(country, district, village, int_warner, int_warned_what) %>%
  arrange(country, district, village, int_warner) %>%
  kable(
    caption = "What was the message?",
      col.names = c("Country", "District", "Village", "Who contacted", "Message")
  ) %>%
  kable_styling(
    full_width = FALSE, 
    bootstrap_options = c("striped", "hover")
  )
```

