# Household survey

```{r}
library(stringr)
library(sf)
library(tidyverse)
library(modelsummary)
library(fixest)
library(glue)
```


```{r}
hh_survey <-
  read_rds(
    file.path(
      path_box,
      "Data",
      "HouseholdSurvey",
      "DataSets",
      "Final",
      "hh-survey.rds"
    )
  ) %>%
  dplyr::filter(survey == "Household Survey")
```

## Sample size

```{r}
hh_survey %>%
  group_by(country, sample_group, wp_intervention_type) %>%
  summarise(
    Villages = n_distinct(village_id),
    Households = n_distinct(household_id),
    `Households with drinking water available` = sum(water_sample, na.rm = TRUE),
    `Drinking water from primary water source` = sum(str_detect(where_collect, "primary"), na.rm = TRUE),
    `Water tested with color wheel` = sum(!is.na(disctcr) | !is.na(discfcr), na.rm = TRUE),
    `Water tested with colorimeter` = sum(!is.na(metertcr) | !is.na(meterfcr), na.rm = TRUE)
  )
```

```{r}
hh_survey %>%
  group_by(country) %>%
  summarise(
    Villages = n_distinct(village_id),
    Households = n_distinct(household_id),
    `Households served by EvAc` = sum(wp_intervention_type != "Non-program", na.rm = TRUE),
    `Households with drinking water available` = sum(water_sample, na.rm = TRUE),
    `Drinking water from primary water source` = sum(str_detect(where_collect, "primary"), na.rm = TRUE),
    `Water tested with color wheel` = sum(!is.na(disctcr) | !is.na(discfcr), na.rm = TRUE),
    `Water tested with colorimeter` = sum(!is.na(metertcr) | !is.na(meterfcr), na.rm = TRUE)
  )
```

## Number of observations

```{r}
hh_survey %>%
  group_by(country) %>%
  summarise(
    N = n(), 
    `Color wheel TCR > 0.2` = mean(disctcr > 0.2, na.rm = TRUE),
    `Color wheel TCR > 0.2` = mean(disctcr > 0.2, na.rm = TRUE),
    `Color wheel FCR > 0.2` = mean(discfcr > 0.2, na.rm = TRUE),
    `Color wheel FCR > 0.2` = mean(discfcr > 0.2, na.rm = TRUE),
    `Colorimeter TCR > 0.2` = mean(metertcr > 0.2, na.rm = TRUE),
    `Colorimeter TCR > 0.2` = mean(metertcr > 0.2, na.rm = TRUE),
    `Colorimeter FCR > 0.2` = mean(meterfcr > 0.2, na.rm = TRUE),
    `Colorimeter FCR > 0.2` = mean(meterfcr > 0.2, na.rm = TRUE)
  ) %>%
  mutate(
    across(
      -c(country, N),
      ~ paste0(round(. * 100, 1), "%")
    ),
    across(everything(), ~ as.character(.))
  ) %>%
  pivot_longer(cols = -country)
```

## Number of water points per household

LW: move this to hh survey

```{r}
wp_distribution <- 
  hh_survey %>%
  mutate(wp_count = if_else(is.na(wp_count), 1L, wp_count + 1L)) %>%
  count(wp_count) %>%
  mutate(percentage = round(n / sum(n) * 100, 1),
        label = paste0(percentage, "%")
  )

total_households <- hh_survey %>%
  mutate(wp_count = if_else(is.na(wp_count), 1L, wp_count + 1L)) %>%
  count(wp_count) %>%
  summarise(total = sum(n)) %>%
  pull(total)

ggplot(wp_distribution, aes(x = "", y = n, fill = as.factor(wp_count))) +
  geom_col(width = 1) +
  coord_polar(theta = "y") +
  geom_text(
    aes(label = label),
    position = position_stack(vjust = 0.5),
    color = "black"                   
  ) +
  scale_fill_viridis_d(option = "D", direction = -1, name = "Water Points Used") +
    labs(
  title = "Distribution of Water Points Used per Household",
  caption = glue("Note: This data includes observations from {total_households} households included to date in the Household Survey."
  )) +
  theme(
    axis.title = element_blank(),
    axis.text = element_blank(),
    axis.ticks = element_blank(),
    panel.grid = element_blank(),
    plot.caption = element_text(hjust = 0, face = "italic") 
  )
```

## chlorination among promoters in hh survey
```{r}
chlorination_promoters <- hh_survey %>%
  group_by(country, promoter_household) %>%
  summarise(
    chl_rate = mean(disctcr > 0.2, na.rm = TRUE),
    n = n(),
    .groups = "drop"
  )

chlorination_promoters
```

## box plot of chlorine test results by color of water
```{r}
hh_survey %>% 
  dplyr::filter(metertcr < 3) %>%
  ggplot(
  aes(x=metertcr_color, y=metertcr)
  ) + geom_boxplot()

hh_survey %>% 
  dplyr::filter(meterfcr < 3) %>%
  ggplot(
  aes(x=meterfcr_color, y=meterfcr)
  ) + geom_boxplot()
```

```{r}
test_vars_c <-
  c(
        "discfcr_c_02", "disctcr_c_02", 
        "meterfcr_c_02", "metertcr_c_02",
        "meterfcr_c_01", "metertcr_c_01"
      )

hh_survey %>%
  # dplyr::filter(make_watersafe_2 == TRUE) %>%
  group_by(make_watersafe_2, intervention_type) %>%
  summarize(
      across(all_of(test_vars_c), ~mean(.,na.rm = TRUE)))
```

## Water treatment

```{r}
hh_survey %>%
  group_by(country, sample_group) %>%
  mutate(
    across(
      matches("make_watersafe_[1-9]"),
      ~ case_when(water_sample ~ replace_na(., FALSE))
    )
  ) %>%
  summarise(
    any = mean(watertreat_any, na.rm = TRUE),
    boil = mean(make_watersafe_1, na.rm = TRUE),
    disp = mean(make_watersafe_2, na.rm = TRUE),
    cl = mean(make_watersafe_3, na.rm = TRUE),
    filter = mean(make_watersafe_4 | make_watersafe_5 |make_watersafe_6, na.rm = TRUE),
    sodis = mean(make_watersafe_7, na.rm = TRUE),
    decant = mean(make_watersafe_8, na.rm = TRUE)
  )
```

```{r}
hh_survey %>%
  mutate(cl_any = make_watersafe_2 | make_watersafe_3) %>%
  group_by(country, sample_group, cl_any) %>%
  summarise(
    across(
      all_of(test_vars),
      ~ mean(., na.rm = TRUE)
    )
  )
```

```{r}
hh_survey %>%
  mutate(
    cl_any = make_watersafe_2 | make_watersafe_3,
    cldisp = make_watersafe_2 %>% replace_na(FALSE)
  ) %>%
  group_by(country, sample_group, cldisp) %>%
  summarise(
    across(
      all_of(test_vars),
      ~ mean(., na.rm = TRUE)
    )
  )
```

```{r}
hh_survey %>%
  dplyr::filter(country == "Malawi", sample_group == "Expansion") %>%
  mutate(dsw_source = wp_intervention_type == "DSW" & str_detect(where_collect, "primary")) %>%
  group_by(dsw_source) %>%
  summarise(
    n = n(),
    mean(disctcr_02, na.rm = TRUE)
  )
  feols(
    disctcr_02 ~ dsw_source,
    cluster = ~ village_id,
    data = .
  )
```


```{r}
hh_survey %>%
  dplyr::filter(country == "Malawi", sample_group == "Expansion") %>%
  mutate(
    cldisp = make_watersafe_2 %>% replace_na(FALSE)
  ) %>%
  tabyl(cldisp, disctcr_02) %>%
  adorn_percentages()
```

